# Generated by Django 5.1.4 on 2025-01-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASAImage',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('media_type', models.CharField(max_length=20)),
                ('service_version', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=225)),
                ('url', models.URLField()),
                ('hdurl', models.URLField()),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
    ]
